CREATE TABLE CATEGORIA(
	ID_CATEGORIA INTEGER PRIMARY KEY,
	NOMBRE_CATEGORIA VARCHAR2(50)
);

CREATE TABLE USUARIO(
	ID_USUARIO INTEGER PRIMARY KEY,
	NOMBRE_USUARIO VARCHAR2(100),
	CORREO_USUARIO VARCHAR2(200),
	TELEFONO_USUARIO VARCHAR2(20),
	PASS_USUARIO VARCHAR2(100)
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INTEGER PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR2(75),
	PRECIO_PRODUCTO INT,
	DESCRIPCION_PRODUCTO VARCHAR2(200),
	ID_CATEGORIA REFERENCES CATEGORIA(ID_CATEGORIA),
	ID_USUARIO REFERENCES USUARIO(ID_USUARIO)
);

SELECT * FROM CATEGORIA;
SELECT * FROM USUARIO;
SELECT * FROM PRODUCTO;

DELETE FROM PRODUCTO WHERE ID_PRODUCTO=2;