CREATE TABLE CATEGORIA(
	ID_CATEGORIA INTEGER PRIMARY KEY,
	NOMBRE_CATEGORIA VARCHAR2(50)
);

CREATE TABLE USUARIO(
	ID_USUARIO INTEGER PRIMARY KEY,
	NOMBRE_USUARIO VARCHAR2(100),
	CORREO_USUARIO VARCHAR2(200),
	TELEFONO_USUARIO VARCHAR2(20),
	PASS_USUARIO VARCHAR2(100)
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INTEGER PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR2(75),
	PRECIO_PRODUCTO INT,
	DESCRIPCION_PRODUCTO VARCHAR2(200),
	ID_CATEGORIA REFERENCES CATEGORIA(ID_CATEGORIA),
	ID_USUARIO REFERENCES USUARIO(ID_USUARIO)
);

SELECT * FROM CATEGORIA;
SELECT * FROM USUARIO;
SELECT * FROM PRODUCTO;

DELETE FROM PRODUCTO WHERE ID_PRODUCTO=2;
SELECT * FROM USUARIO WHERE CORREO_USUARIO="usuario@mail.com";

INSERT INTO CATEGORIA VALUES (1, "Detergentes");
INSERT INTO CATEGORIA VALUES (2, "Shampoos");
INSERT INTO CATEGORIA VALUES (3, "Jabones");
INSERT INTO CATEGORIA VALUES (4, "Desinfectantes");

INSERT INTO PRODUCTO VALUES (1, "Omo", 2990, "Detergente para lavado de ropa color", 1, 1);
INSERT INTO PRODUCTO VALUES (2, "Loreal", 3500, "Shampoo pelo delicado", 2, 1);
INSERT INTO PRODUCTO VALUES (3, "Family Care", 1990, "Jabon para lavado de manos", 3, 1);
INSERT INTO PRODUCTO VALUES (4, "Lysoform", 2490, "Desinfectante ambientes", 4, 1);
